### ISSUE TITLE
Reconcilation problem

### ISSUE THREAD

**Issue by ivan-kleshnin** [paldepind/snabbdom#106]
I'm considering **snabbdom** as a **virtual-dom** replacement. I've hit some problem (or bug) with node reconcilation. It would require tons of words to explain without a video so here is one:

https://drive.google.com/file/d/0B9bW0B92XgnAbnM2LXNZYWZ6NzQ/view

The first half (game board with black top-left corner) features **virtual-dom** based code and the second half (game board without such corner) features **snabbdom** based code. 

As you can see there, **snabbdom** reconciles a parent `span.cell` 

```html
<span class="cell" data-row="0" data-col="0">  <-- this one should not reconcile at card flip
  <span class="card flipper shaker" data-state="0">
    <span class="front">?</span>
    <span class="back">F</span>
  </span>
</span>
```

at the time child `span.card` is changing. This reconcilation is unnecessary because no attribute of the parent `span.cell` is changing. And it interrupts CSS transition destroying animation alltogether.

The code for both examples is obviously the same, only API stuff were touched. 

**virtual-dom** version: https://github.com/Paqmind/memory-game/tree/styles
**snabbdom** version: https://github.com/Paqmind/memory-game/tree/vdom-experiments

**Comment by ivan-kleshnin** [comment]
Tried to add `key` property – still no success.

```js
let renderCell = curry((i, j, cell) => {
  let cellAttrs = {..., key: String(i) + "-" +String(j)}
  if (cell[1] == 0) {
    return span(".cell", cellAttrs, [
      ...
    ])
  } else if (cell[1] == 1) {
    return span(".cell", cellAttrs, [
      ...
    ])
  } else {
    return span(".cell", cellAttrs, [
      ...
    ])
  }
})

let renderBoard = (board) => {
  let rowsM = board.length
  let colsN = board[0] ? board[0].length : 0
  return div(`.board.rows-${rowsM}.cols-${colsN}`,
    chainIndexed((r, i) => mapIndexed((c, j) => renderCell(i, j, c), r), board)
  )
}
```

**Comment by ivan-kleshnin** [comment]
@paldepind, @TylorS seems there is a bug.

Broken demo:
https://gist.github.com/ivan-kleshnin/ac0ae731b3b324db0c258349dd2daf8f

Working demo:
https://gist.github.com/ivan-kleshnin/97c1778f4363fdb2f504f476fffda521

### Comments

#### Working

```js
span(".cell", [
  span({attrs: {"class": "card flipper shaker", "data-state": 0}}, ...)
]) 
```

changes to 

```js
span(".cell", [
  span({attrs: {"class": "card", "data-state": 1}}, ...)
]) 
```

**`span.card` reconciles [ok]**

#### Broken

```js
span(".cell", [
  span({attrs: {"class": "card", "data-state": 0}}, ...)
]) 
```

changes to 

```js
span(".cell", [
  span(".card", {attrs: {"data-state": 1}}, ...)
]) 
```

**Parent `span.cell` reconciles... [wtf?]**

**Comment by paldepind** [comment]
Thank you for reporting this. This does indeed look like a bug. I'll look into it.

**Comment by whitecolor** [comment]
+1

**Comment by bloodyKnuckles** [comment]
May be a simplified version of glitch here: 

https://gist.github.com/bloodyKnuckles/3b351d862b3ecbc1b6a067420d70bad9

**Comment by bloodyKnuckles** [comment]
I discovered, with the new `sameVnode` function, when changing from using `attrs` to `sel` for the class, the `class` attribute is removed from the rendered element.

Here's one way to fix: change *modules/attributes.js* `removeAttribute` code to:

```
  for (key in oldAttrs) {
    if (!(key in attrs)) {
      if ('class' === key && -1 < oldAttrs[key].split(/ +/).indexOf(vnode.sel.split('.')[1]))
        vnode.data.attrs.class = vnode.sel.split('.')[1];
        // elm.className = vnode.sel.split('.')[1]; // which is better ??
      else
        elm.removeAttribute(key);
    }
  }
```

**Comment by AlexGalays** [comment]
Any news @paldepind  ?

**Comment by paldepind** [comment]
Sorry, I haven't looked at this. Thank you for reminding me @AlexGalays and thanks to @bloodyKnuckles  for the analysis :trophy: 

I'll look at it in a few couple of days :soon:

**Comment by paldepind** [comment]
The classes and id's put in the selector string when creating `vnode`s are supposed to be static. This helps Snabbdom match up new and old elements in the absence of keys. Dynamic classes are best set with the classes module or similar. So that part, I'd say is by design.

Regarding the "parent incorrectly reconciled"-problem. As far as I can figure out Snabbdom actually does not modify the parent element at all. I.e. it behaves correctly. What is highlighted in the Chrome elements debugger seems to be subtree modifications. Among other things I've tried setting element breakpoints on both attribute- and subtree-modifications in the Chrome debugger and only the subtree modification breakpoint is triggered. So the highlighting does not indicate that the parent is being modified. It only indicates that a _child_ to the parent has been replaced with a different element.

I think the only problem is that the current documentation does not emphasize that classes in the selector are supposed to be static. Actually it's not mentioned at all :disappointed:

**Comment by AlexGalays** [comment]
Cool, makes sense.

Indeed, it's perhaps unclear for someone new whether she should use a className in the selector or the class module.

**Comment by ivan-kleshnin** [comment]
> So the highlighting does not indicate that the parent is being modified. It only indicates that a child to the parent has been replaced with a different element.

I believe this is not true. With virtual DOM (behaving correct) highlighting was indicating child element only. So the parent element IS updated which is confirmed by broken behavior.

**Comment by ivan-kleshnin** [comment]
> The classes and id's put in the selector string when creating vnodes are supposed to be static

contradicts

> Dynamic classes are best set with the classes module or similar

I guess animations will be broken with `classes`?!

**Comment by Hypnosphi** [comment]
@ivan-kleshnin "static" is an antonym of "dynamic"

**Comment by ivan-kleshnin** [comment]
@Hypnosphi so what? How does module addition( which just generate string constant) change the requirement?

**Comment by Hypnosphi** [comment]
What is meant here is that the classes in selector are the ones that always remain present, not that other ones can't be added dynamically.

**Comment by paldepind** [comment]
> 1) I'm afraid this is not true. Chrome highlights replaced nodes not just somehow affected ones. Same case with VirtualDOM (first half of the video) is highlighted differently.

If the child list of an element is modified (for instance if an element in the list is replaced) Chrome will highlight that element. So if a child element is modified the parent will not highlight. But if a child element is replaced or removed the parent will highlight because it is a modification to it's list of child elements.

[The `renderCell` function](https://github.com/Paqmind/memory-game/blob/d04d8bd7b68f47d46d8547a8b1577e1183987f14/src/app.js#L69) in your first example changes classes by returning different selector strings, this causes Snabbdom to replace the element which causes Chrome to highlight the parent.

[Here is a RequireBin](http://requirebin.com/?gist=44ef67692abdbf2fc56e7261853f53f7) for you `snabbdom.ex1.js` example. Try right clicking on the element that you think is incorrectly changed and add breakpoints for "Subtree Modifications" and "Attribute Modifications". Then press the button that triggers the patch. You will see that the only breakpoint triggered are from subtree modifcations.

>2)
>> The classes and id's put in the selector string when creating vnodes are supposed to be static
>
> contradicts
>
>> Dynamic classes are best set with the classes module or similar

Sorry, but I don't see the contradiction? In the first quote I say that the selector string is for _static_ classes and in the second quote I say that the classes module is for _dynamic_ classes.

> @Hypnosphi so what? How does module which just generates string constant change the requirement?

The class module does not just generate a string constant. [See it's source](https://github.com/paldepind/snabbdom/blob/master/modules/class.js). It uses `classList` to add and remove classes based on the dictionary that you give it.

**Comment by paldepind** [comment]
Yes, @Hypnosphi. That was what I meant. I'm sorry if I wasn't clear enough @ivan-kleshnin.

**Comment by ivan-kleshnin** [comment]
> Sorry, but I don't see the contradiction? In the first quote I say that the selector string is for static classes and in the second quote I say that the classes module is for dynamic classes.

Sorry, I thought you meant 3rd party module – now I see what you mean.

**Comment by paldepind** [comment]
> My bad, I thought you meant particular 3rd party module... – now I see what you mean.
I was context switching hence the stupidity :)

No problem :smile: 

> So to recap: in VirtualDOM child span is updated, and in Snabbdom child span is replaced. That explains what we see. To avoid child span reconcilations (and fix animation) – changes should not affect selector string. As I need to change className – I should use [`class`](https://github.com/paldepind/snabbdom/blob/master/modules/class.js) module instead of selector.

Yes, excactly. The same as what you did in the "broken" vs. "working" example earlier. If you still experience errors then let me know! If you're doing animations the [style](https://github.com/paldepind/snabbdom#the-style-module) might also be useful to you. It has a couple of features especially made for making animations easier.

I'm sorry you had to wait so long to get a proper response here.
