### ISSUE TITLE
Range input rendering bug

### ISSUE THREAD

**Issue by ds300** [paldepind/snabbdom#139]
The order in which props are traversed when applying them to range input elements matters for some reason.

e.g.

```js
var patch = require('snabbdom').init([
  require('snabbdom/modules/props'),
]);

var h = require('snabbdom/h');

var elem = h('div', [
  h('input', {props: {type: "range", min: 100, max: 270, value: 170}}), // renders correctly
  h('input', {props: {type: "range", min: 100, value: 170, max: 270}}), // value ends up being 100
]);

patch(document.body.children[0], elem);
```

http://requirebin.com/?gist=909a5f02c4548a48897d0c2b6a45778f

**Comment by paldepind** [comment]
Thank you for reporting this. The order of the keys in `props` changes the order in which the properties are being set on the DOM element. I think the difference you are seeing must be due to how the browser handles setting the properties.

I tried switching your example from using the `props` module to using the `attributes` module. This seems to fix the problem. http://requirebin.com/?gist=ce5d1009a4bc79e3a08fca26da931e4c

**Comment by ds300** [comment]
:+1: on talking about attrs a bit more. Might help people coming from React who aren't so familiar with the vanilla DOM api.
