### ISSUE TITLE
Support for rendering custom attributes.

### ISSUE THREAD

**Issue by ismail-codar** [paldepind/snabbdom#16]
```javascript
h('input', {props:{"data-id": "test-data-id", "id": "test-input"}})
```
 outputs only 
```html
<input id="test-input">
```
 data-id attribute is not rendering. http://requirebin.com/?gist=72ff6f4487069d2239cf Sometime users want to custom attributes on dom nodes.

Related issue: https://github.com/paldepind/snabbdom/issues/10

**Comment by paldepind** [comment]
Yes. You are correct. This is because the property module sets properties on DOM nodes and not HTML attributes. @yelouafi has written an attribute module that I've just merged and published.

I haven't tested it myself but it should be possible to add data attributes like this:

```js
h('input', {attrs: {"data-id": "test-data-id"}, props: {id: "test-input"}})
```

Also [check out the documentation](https://github.com/paldepind/snabbdom#the-attributes-module).

Let me know if this solves your issue :)

**Comment by ismail-codar** [comment]
Sorry http://requirebin.com/?gist=72ff6f4487069d2239cf  working now.
