### ISSUE TITLE
Support JSX compilation

### ISSUE THREAD

**Issue by theadam** [paldepind/snabbdom#6]
JSX almost works already using a pragma that instructs the compiler to use ```snabbdom/h```, there are just 2 edge cases I have found.
* If no attributes are added to a JSX element, the data argument is null.  This causes snabbdom to throw an error.
* Children are not provided as an array, they are provided as any arguments after the selector and data.

A basic example of what this would look like can be found [here](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=%2F**%20%40jsx%20h%20*%2F%0A%0A%3Cdiv%3E%0A%20%20%3Cspan%20testProp%3D%22testval%22%20%2F%3E%0A%20%20%3Cspan%20%2F%3E%0A%3C%2Fdiv%3E).

**Comment by yelouafi** [comment]
FYI, i wrote a small module that transforms Babel/JSX templates into snabbdom vnodes [yelouafi/snabbdom-jsx](https://github.com/yelouafi/snabbdom-jsx).

There is a little more than the pragma instruction, i had to solve things like mapping JSX attributes to data attributes in the vnode (event listeners, props, classes ...) and also define a component spec to support creating and nesting JSX components (i used simple functions instead of classes as in React).

There is also a [todomvc example](https://github.com/yelouafi/snabbdom-jsx/tree/master/examples/todomvc) using Elm architecture and JSX templates.

**Comment by avesus** [comment]
Shure, supporting the `null` argument is the best choice because it allows using pure Babel without any transforms..

**Comment by paldepind** [comment]
snabbdom-jsx looks awesome to me. I've just added it to the readme.

**Comment by avesus** [comment]
Mithril *was* my mind = blown. The Elm Architecture and Snabbdom's component namespacing of vdom attributes are no words at all. Thank you guys. Definitely pure JSX is bad use comparing to snabbdom-jsx.

**Comment by avesus** [comment]
> I've just added it to the readme.

I fell that the history is maked right here right now :-) Wonderful!

@paldepind also there is a wonderful introductory example to note written by @yelouafi , https://github.com/yelouafi/snabbdom-todomvc and https://medium.com/@yelouafi/react-less-virtual-dom-with-snabbdom-functions-everywhere-53b672cb2fe3

**Comment by paldepind** [comment]
@avesus I've mentioned that splendid article in [this readme](https://github.com/paldepind/functional-frontend-architecture#documentation) because I think it belongs better there. But maybe adding it to the readme of Snabbdom would be appropriate as well?

**Comment by finnsson** [comment]
I wrote a small JSX Babel-plugin for snabbdom (https://github.com/finnsson/babel-snabbdom-jsx) that might be interesting to someone. Emitting code for `snabbdom/h`.

**Comment by paldepind** [comment]
The readme links to both the snabbdom-jsx and babel-snabbdom-jsx. I'll close this issue.
